version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U admin' ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app
      - db
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - ./src:/app/src
    restart: always
    container_name: app
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - db
    networks:
      - app

volumes:
  db_data:
    name: db_data
    driver: local
  db_logs:
    name: db_logs
    driver: local

networks:
  db:
  app:
    driver: bridge