version: '3.3'

services:

  db:
    image: arteom/postgres:latest
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes: 
      - ./postgres/postgres_data:/var/lib/postgresql/data
      - ./postgres/logs:/var/log/postgresql
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    networks:
      - service
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -d db -U admin"]
       interval: 5s
       timeout: 5s
       retries: 5

  rest-service:
    image: arteom/rest-service:latest
    ports: 
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
    restart: always
    networks:
      - service

networks:
  service:
    driver: bridge