version: '3.3'

networks:
  service:
    driver: bridge

services:

  db:
    image: arteom/postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - service
    restart: always
    volumes:
      - ./node_modules:/app/node_modules
      - ./postgres/postgres_data:/var/lib/postgresql/data
      - ./postgres/logs:/var/logs/postgresql/postgresql.logs
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U admin' ]
      interval: 5s
      timeout: 5s
      retries: 10
  
  rest-service:
    image: arteom/rest-service:0.0.2
    restart: always
    container_name: rest-service
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - service
    depends_on:
      - db